# Default configuration for holograms.yml
# This will be created if holograms.yml doesn't exist

# Example holograms
example:
  world: world
  x: 0
  y: 65
  z: 0
  lines:
    - "&b&lServer Rules"
    - "&f1. Be respectful to other players"
    - "&f2. No griefing or stealing"
    - "&f3. Have fun!"

welcome:
  world: world
  x: 10
  y: 65
  z: 10
  lines:
    - "&a&lWelcome to the server!"
    - "&fUse &b/hologram help &ffor commands"
    - "&7Created with FrostGUI"
